#limiting met_pt cut to 300GeV, test at c2v=1.5
objsel:
  all_events: '(events.Pass_MetTriggers == 1) | ~(events.Pass_MetTriggers == 1)'
  MET_trigger: '(events.Pass_MetTriggers == 1)'
  nGoodAK8geq2: '(events.nGoodAK8 >= 2)'
  has_vbs_pair: 'ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'
  MET_pt_loose: '(events.Met_pt > 100)'
  H_score_loose:  '(events.HiggsScore > 0.1)'
  V1_score_loose: '(events.V1Score > 0.1)'
  AK4_Bveto: '(events.Pass_NoAK4BJet == 1)'

med0_objsel:
  objsel: '(events.Pass_MetTriggers == 1) & (events.Met_pt > 100) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1) & (events.nGoodAK8 >= 2)'


med1_metpt:
  objsel: '(events.Pass_MetTriggers == 1) & (events.Met_pt > 100) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1) & (events.nGoodAK8 >= 2)'
  MET_pt_150: '(events.Met_pt>150)'
  
