preselection:
  all_events: '(events.Pass_MetTriggers == 1) | ~(events.Pass_MetTriggers == 1)'
  MET_trigger: '(events.Pass_MetTriggers == 1)'
  nGoodAK8geq2: '(events.nGoodAK8 >= 2)'
  has_vbs_pair: 'ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'
  MET_pt_presel: '(events.Met_pt > 100)'
  MET_signif_presel: '(events.Met_significance > 20)'
  loose_HScore: '(events.HiggsScore > 0.1)'
  loose_VScore: '(events.V1Score > 0.1)'
  ak4_bveto: '(events.Pass_NoAK4BJet == 1)'

tight:
  objsel: '(events.Pass_MetTriggers == 1) & (events.Met_pt > 100) & (events.Met_significance > 20) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1) & (events.nGoodAK8 >= 2)'
  MET_pt_250: '(events.Met_pt > 250)'
  HMET_dphi_p6: '(var["HMET_dphi"] >0.6)'
  V1MET_dphi_p6: '(var["V1MET_dphi"] >0.6)'
  Hscore: '(events.HiggsScore > 0.6)'
  V1score: '(events.V1Score > 0.6)'
  
no_metsignif:
  objsel: '(events.Pass_MetTriggers == 1) & (events.Met_pt > 100) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1) & (events.nGoodAK8 >= 2)'
  MET_pt_250: '(events.Met_pt > 250)'
  HMET_dphi_p6: '(var["HMET_dphi"] >0.6)'
  V1MET_dphi_p6: '(var["V1MET_dphi"] >0.6)'
  Hscore: '(events.HiggsScore > 0.6)'
  V1score: '(events.V1Score > 0.6)'