
MET_met300_full:
  all_events: '(events.Pass_MetTriggers == 1) | ~(events.Pass_MetTriggers == 1)'
  objsel: '(events.Pass_MetTriggers == 1) & (events.Met_pt > 100) & (events.Met_significance > 20) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'
  MET_pt_tight: 'events.Met_pt > 300'
  vbsj_deta: '(var["vbsj_deta"]>2.5)'
  H_MET_dphi: 'var["HMET_dphi"] > 0.6'
  V1_MET_dphi: 'var["V1MET_dphi"] > 0.6'
  cut_H: 'events.HiggsScore > 0.6'
  cut_V1: 'events.V1Score > 0.6'

MET_met300_objsel:
  all_events: '(events.Pass_MetTriggers == 1) | ~(events.Pass_MetTriggers == 1)'
  MET_trigger: '(events.Pass_MetTriggers == 1)'
  nGoodAK8geq2: '(events.nGoodAK8 >= 2)'
  has_vbs_pair: 'ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'
  MET_pt_loose: '(events.Met_pt > 100)'
  MET_significance_loose: '(events.Met_significance > 20)'
  H_score_loose:  '(events.HiggsScore > 0.1)'
  V1_score_loose: '(events.V1Score > 0.1)'
  AK4_Bveto: '(events.Pass_NoAK4BJet == 1)'

MET_met300_objsel_notrigger:
  fail_MET_trigger: '~(events.Pass_MetTriggers == 1)'
  no_MET_trigger: '(events.nGoodAK8 >= 2) & (events.Met_pt > 100) & (events.Met_significance > 20) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'

  
MET_met300_notrigger:
  no_MET_trigger: '(events.nGoodAK8 >= 2) & (events.Met_pt > 100) & (events.Met_significance > 20) & (events.Pass_NoAK4BJet == 1) & (events.HiggsScore > 0.1) & (events.V1Score > 0.1) & ak.all(events.vbs_idx_max_Mjj > -1, axis=1)'
  fail_MET_trigger: '~(events.Pass_MetTriggers == 1)'
  MET_pt_2: '(events.Met_pt > 200)'
  MET_pt_3: '(events.Met_pt > 300)'
